### PR TITLE
fix: inputs.type only support string

### PR DESCRIPTION
**Pull request by jianshen92**
https://docs.github.com/en/actions/learn-github-actions/expressions#about-expressions

### CODE REVIEW

**Comment by frostming** [comment]
These two styles are equivalent, so what is the problem?

**Comment by aarnphm** [comment]
echo frost question here

**Comment by jianshen92** [comment]
Few findings here,
1. i dont think `if: inputs.build == true` works? without the `${{ }}` syntax GH action just evaluates the whole thing as string.
2. there is no `inputs.type` so everything in inputs is a string so we can't use `true` or `false`, it has to be `'true'`  💯 (: https://stackoverflow.com/questions/76292948/github-action-boolean-input-with-default-value

**Comment by jianshen92** [comment]
PTAL @aarnphm

**Comment by frostming** [comment]
From the link you pasted: 

> When you use expressions in an if conditional, you may omit the ${{ }} expression syntax because GitHub Actions automatically evaluates the if conditional as an expression. However, this rule does not apply everywhere.

while changing `true` to `'true'` is a valid fix and the cause of the problem.

**Comment by jianshen92** [comment]
> From the link you pasted:
> 
> > When you use expressions in an if conditional, you may omit the ${{ }} expression syntax because GitHub Actions automatically evaluates the if conditional as an expression. However, this rule does not apply everywhere.
> 
> while changing `true` to `'true'` is a valid fix and the cause of the problem.

got it, missed that part. I was confused by this example

> [Example of success](https://docs.github.com/en/actions/learn-github-actions/expressions#example-of-success)
> steps:
>   ...
>   - name: The job has succeeded
>     if: ${{ success() }}

**Review by aarnphm — APPROVED** [review]

**Pull request merged**
